### PR TITLE
Add new API to know if an email has a ticket for event(s)

### PR DESCRIPTION
**Pull request by marcoacierno**
API version of our DB query for checking if an email has an admission ticket for an event.

This API is a bit more advanced than the DB equivalent:

https://github.com/pythonitalia/pycon/blob/324c1307639d1d92e11f67c685fc29f1e7b5a277/backend/pretix/db.py#L8

The API supports sending an **array** of events to check against. This is needed because for voting we want to check if the user has a ticket for pycon italia 2022, but also if they had a ticket for pycon 10 and pycon 9 we want to allow them to vote too.

### CODE REVIEW

**Review by patrick91 — APPROVED** [review]

**Review by estyxx — APPROVED** [review]
LGTM 👍

**Pull request merged**
